language: generic
sudo: required
services:
  - docker

before_install:
 - docker build -t dreacotnigeria/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dreacotnigeria/react-test npm test -- --coverage

after_success:
  - docker build -t dreacotnigeria/multi-client ./client
  - docker build -t dreacotnigeria/multi-nginx ./nginx
  - docker build -t dreacotnigeria/multi-server ./server
  - docker build -t dreacotnigeria/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push dreacotnigeria/multi-client
  - docker push dreacotnigeria/multi-nginx
  - docker push dreacotnigeria/multi-server
  - docker push dreacotnigeria/multi-worker